server:
  port: ${DEV_INTER_PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:miphi}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: true
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework: ERROR
    com.example: DEBUG
